import { useEffect, useRef, useState } from "react";
import { createFileRoute, Navigate } from "@tanstack/react-router";
import { useAuth } from "@/hooks/use-auth";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { Slider } from "@/components/ui/slider";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Settings as SettingsIcon, Upload, X, RefreshCw, Save } from "lucide-react";
import { toast } from "sonner";
import autoTable from "jspdf-autotable";
import {
  loadTemplate, invalidateTemplateCache, createBrandedPdf, applyTemplateChrome, tableHeadFill,
  DEFAULT_TEMPLATE, type DocumentTemplate,
} from "@/lib/pdf-template";
import {
  THEME_PRESETS, FONT_OPTIONS, loadStoredTheme, saveStoredTheme, type StoredTheme,
} from "@/lib/theme";

export const Route = createFileRoute("/_app/settings")({
  component: SettingsPage,
});

function SettingsPage() {
  const { loading, canView, canDo } = useAuth();
  const canManage = canDo("manage_document_templates");
  const [tpl, setTpl] = useState<DocumentTemplate | null>(null);
  const [saving, setSaving] = useState(false);
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);
  const previewTimer = useRef<any>(null);

  useEffect(() => { loadTemplate(true).then(setTpl); }, []);

  // Debounced live preview
  useEffect(() => {
    if (!tpl) return;
    clearTimeout(previewTimer.current);
    previewTimer.current = setTimeout(() => generatePreview(tpl).then(setPreviewUrl), 250);
    return () => clearTimeout(previewTimer.current);
  }, [tpl]);

  if (loading) return null;
  if (!canView("settings")) return <Navigate to="/dashboard" />;
  if (!tpl) return <div className="p-6 text-sm text-muted-foreground">Loading template…</div>;

  const set = <K extends keyof DocumentTemplate>(k: K, v: DocumentTemplate[K]) =>
    setTpl((t) => (t ? { ...t, [k]: v } : t));

  const onPickFile = async (key: "logo_data_url" | "watermark_image_data_url", file: File) => {
    const dataUrl = await fileToDataUrl(file);
    set(key, dataUrl);
  };

  const save = async () => {
    if (!tpl) return;
    if (!canManage) { toast.error("You don't have permission to edit templates"); return; }
    setSaving(true);
    const { id, created_at, updated_at, ...rest } = tpl as any;
    const payload = { ...rest, updated_by: (await supabase.auth.getUser()).data.user?.id };
    const { error } = await supabase
      .from("document_templates" as any)
      .update(payload)
      .eq("id", id);
    setSaving(false);
    if (error) { toast.error(error.message); return; }
    invalidateTemplateCache();
    toast.success("Template saved · applies to all new PDFs");
  };

  const reset = () => setTpl((t) => (t ? { ...DEFAULT_TEMPLATE, id: t.id, name: t.name } : t));

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h1 className="flex items-center gap-2 text-2xl font-bold tracking-tight">
            <SettingsIcon className="h-6 w-6" /> Document Template
          </h1>
          <p className="text-sm text-muted-foreground">
            Branding & layout applied to every PDF generated by the system (reports, gate passes, asset details, depreciation schedules).
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="outline" onClick={reset} disabled={!canManage}><RefreshCw className="mr-2 h-4 w-4" />Reset</Button>
          <Button onClick={save} disabled={!canManage || saving}><Save className="mr-2 h-4 w-4" />{saving ? "Saving…" : "Save changes"}</Button>
        </div>
      </div>

      {!canManage && (
        <Card className="border-amber-300 bg-amber-50 p-3 text-sm text-amber-900">
          You can preview the active template but you don't have the <strong>manage_document_templates</strong> right needed to edit it. Ask an administrator to grant it from the Users module.
        </Card>
      )}

      <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(0,1fr)]">
        <Card className="p-4">
          <Tabs defaultValue="brand">
            <TabsList className="grid h-auto w-full grid-cols-2 gap-1 sm:grid-cols-3 lg:grid-cols-6">
              <TabsTrigger value="brand">Branding</TabsTrigger>
              <TabsTrigger value="header">Header / Footer</TabsTrigger>
              <TabsTrigger value="watermark">Watermark</TabsTrigger>
              <TabsTrigger value="layout">Layout</TabsTrigger>
              <TabsTrigger value="appearance">Appearance</TabsTrigger>
              <TabsTrigger value="guides">User guides</TabsTrigger>
            </TabsList>


            <fieldset disabled={!canManage} className="space-y-4">

            <TabsContent value="brand" className="space-y-4 pt-4">
              <div className="space-y-2">
                <Label>Organization name</Label>
                <Input value={tpl.organization_name} onChange={(e) => set("organization_name", e.target.value)} />
              </div>
              <div className="space-y-2">
                <Label>Logo</Label>
                {tpl.logo_data_url ? (
                  <div className="flex items-center gap-3 rounded border p-2">
                    <img src={tpl.logo_data_url} alt="Logo" className="h-12 w-auto rounded bg-white" />
                    <Button size="sm" variant="ghost" onClick={() => set("logo_data_url", null)}>
                      <X className="mr-1 h-4 w-4" /> Remove
                    </Button>
                  </div>
                ) : (
                  <label className="flex cursor-pointer items-center gap-2 rounded border border-dashed p-3 text-sm text-muted-foreground hover:bg-muted/50">
                    <Upload className="h-4 w-4" /> Upload PNG/JPG (recommended &lt; 200 KB)
                    <input type="file" accept="image/*" className="hidden" onChange={(e) => e.target.files?.[0] && onPickFile("logo_data_url", e.target.files[0])} />
                  </label>
                )}
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div className="space-y-2">
                  <Label>Logo position</Label>
                  <Select value={tpl.logo_position} onValueChange={(v) => set("logo_position", v as any)}>
                    <SelectTrigger><SelectValue /></SelectTrigger>
                    <SelectContent>
                      <SelectItem value="left">Left</SelectItem>
                      <SelectItem value="center">Center</SelectItem>
                      <SelectItem value="right">Right</SelectItem>
                      <SelectItem value="none">Hidden</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-2">
                  <Label>Logo max height (mm) — {tpl.logo_max_height}</Label>
                  <Slider value={[tpl.logo_max_height]} min={6} max={40} step={1} onValueChange={([v]) => set("logo_max_height", v)} />
                </div>
              </div>
              <div className="space-y-2">
                <Label>Primary color</Label>
                <div className="flex items-center gap-2">
                  <input type="color" value={tpl.primary_color} onChange={(e) => set("primary_color", e.target.value)} className="h-9 w-12 cursor-pointer rounded border bg-transparent" />
                  <Input value={tpl.primary_color} onChange={(e) => set("primary_color", e.target.value)} className="font-mono" />
                </div>
              </div>
            </TabsContent>

            <TabsContent value="header" className="space-y-4 pt-4">
              <div className="flex items-center justify-between">
                <Label>Show header</Label>
                <Switch checked={tpl.header_show} onCheckedChange={(v) => set("header_show", v)} />
              </div>
              <div className="space-y-2">
                <Label>Header text (right side, falls back to organization name)</Label>
                <Input value={tpl.header_text} onChange={(e) => set("header_text", e.target.value)} placeholder="e.g. Acme Holdings Ltd · Confidential" />
              </div>
              <div className="flex items-center justify-between">
                <Label>Show footer</Label>
                <Switch checked={tpl.footer_show} onCheckedChange={(v) => set("footer_show", v)} />
              </div>
              <div className="space-y-2">
                <Label>Footer text</Label>
                <Textarea rows={2} value={tpl.footer_text} onChange={(e) => set("footer_text", e.target.value)} placeholder="© 2026 Acme Holdings · Generated by AssetFlow" />
              </div>
              <div className="flex items-center justify-between">
                <Label>Show page numbers</Label>
                <Switch checked={tpl.show_page_numbers} onCheckedChange={(v) => set("show_page_numbers", v)} />
              </div>
              <div className="flex items-center justify-between">
                <Label>Show generated-at timestamp</Label>
                <Switch checked={tpl.show_generated_at} onCheckedChange={(v) => set("show_generated_at", v)} />
              </div>
            </TabsContent>

            <TabsContent value="watermark" className="space-y-4 pt-4">
              <div className="space-y-2">
                <Label>Watermark text</Label>
                <Input value={tpl.watermark_text} onChange={(e) => set("watermark_text", e.target.value)} placeholder="e.g. CONFIDENTIAL" />
              </div>
              <div className="space-y-2">
                <Label>Watermark image (optional, overlay)</Label>
                {tpl.watermark_image_data_url ? (
                  <div className="flex items-center gap-3 rounded border p-2">
                    <img src={tpl.watermark_image_data_url} alt="Watermark" className="h-12 w-auto rounded bg-white" />
                    <Button size="sm" variant="ghost" onClick={() => set("watermark_image_data_url", null)}>
                      <X className="mr-1 h-4 w-4" /> Remove
                    </Button>
                  </div>
                ) : (
                  <label className="flex cursor-pointer items-center gap-2 rounded border border-dashed p-3 text-sm text-muted-foreground hover:bg-muted/50">
                    <Upload className="h-4 w-4" /> Upload watermark image
                    <input type="file" accept="image/*" className="hidden" onChange={(e) => e.target.files?.[0] && onPickFile("watermark_image_data_url", e.target.files[0])} />
                  </label>
                )}
              </div>
              <div className="space-y-2">
                <Label>Position</Label>
                <Select value={tpl.watermark_position} onValueChange={(v) => set("watermark_position", v as any)}>
                  <SelectTrigger><SelectValue /></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="none">None</SelectItem>
                    <SelectItem value="center">Center</SelectItem>
                    <SelectItem value="diagonal">Diagonal</SelectItem>
                    <SelectItem value="repeated">Repeated pattern</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label>Opacity — {Math.round(tpl.watermark_opacity * 100)}%</Label>
                <Slider value={[tpl.watermark_opacity * 100]} min={2} max={60} step={1} onValueChange={([v]) => set("watermark_opacity", v / 100)} />
              </div>
            </TabsContent>

            <TabsContent value="layout" className="space-y-4 pt-4">
              <div className="grid grid-cols-2 gap-3">
                <div className="space-y-2">
                  <Label>Font family</Label>
                  <Select value={tpl.font_family} onValueChange={(v) => set("font_family", v as any)}>
                    <SelectTrigger><SelectValue /></SelectTrigger>
                    <SelectContent>
                      <SelectItem value="helvetica">Helvetica (sans-serif)</SelectItem>
                      <SelectItem value="times">Times (serif)</SelectItem>
                      <SelectItem value="courier">Courier (monospace)</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-2">
                  <Label>Base font size — {tpl.base_font_size}pt</Label>
                  <Slider value={[tpl.base_font_size]} min={7} max={16} step={1} onValueChange={([v]) => set("base_font_size", v)} />
                </div>
                <div className="space-y-2">
                  <Label>Orientation</Label>
                  <Select value={tpl.orientation} onValueChange={(v) => set("orientation", v as any)}>
                    <SelectTrigger><SelectValue /></SelectTrigger>
                    <SelectContent>
                      <SelectItem value="portrait">Portrait</SelectItem>
                      <SelectItem value="landscape">Landscape</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-2">
                  <Label>Paper size</Label>
                  <Select value={tpl.paper_size} onValueChange={(v) => set("paper_size", v as any)}>
                    <SelectTrigger><SelectValue /></SelectTrigger>
                    <SelectContent>
                      <SelectItem value="a4">A4</SelectItem>
                      <SelectItem value="letter">Letter</SelectItem>
                      <SelectItem value="legal">Legal</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>
              <div className="grid grid-cols-4 gap-3">
                {(["margin_top", "margin_right", "margin_bottom", "margin_left"] as const).map((k) => (
                  <div className="space-y-2" key={k}>
                    <Label className="capitalize">{k.replace("margin_", "")} (mm)</Label>
                    <Input type="number" min={0} max={60} value={tpl[k]} onChange={(e) => set(k, Number(e.target.value))} />
                  </div>
                ))}
              </div>
              <p className="text-xs text-muted-foreground">
                Note: list-style PDFs (asset list, reports) keep their landscape orientation; portrait/landscape choice here is the default for single-record documents.
              </p>
            </TabsContent>

            </fieldset>

            <TabsContent value="appearance" className="space-y-4 pt-4">
              <AppearancePanel />
            </TabsContent>

            <TabsContent value="guides" className="space-y-4 pt-4">
              <UserGuidesPanel />
            </TabsContent>
          </Tabs>

        </Card>

        <Card className="flex h-[800px] flex-col p-3">
          <div className="mb-2 flex items-center justify-between">
            <p className="text-sm font-medium">Live preview (sample gate pass)</p>
            <p className="text-xs text-muted-foreground">Updates as you type</p>
          </div>
          {previewUrl ? (
            <iframe key={previewUrl} src={previewUrl} className="h-full w-full flex-1 rounded border bg-white" title="PDF preview" />
          ) : (
            <div className="flex flex-1 items-center justify-center text-sm text-muted-foreground">Rendering…</div>
          )}
        </Card>
      </div>
    </div>
  );
}

function fileToDataUrl(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const r = new FileReader();
    r.onload = () => resolve(String(r.result));
    r.onerror = reject;
    r.readAsDataURL(file);
  });
}

async function generatePreview(tpl: DocumentTemplate): Promise<string> {
  const { doc, startY, pageWidth } = createBrandedPdf({
    template: tpl,
    title: "SAMPLE GATE PASS",
    subtitle: "Pass No: GP-2026-000123",
  });
  autoTable(doc, {
    startY,
    head: [["Field", "Value"]],
    body: [
      ["Asset", "LP-001 · Dell Latitude 7440"],
      ["Branch", "Head Office"],
      ["Destination", "Client site — Garden City"],
      ["Reason", "Field installation"],
      ["Expected return", new Date(Date.now() + 5 * 86400000).toLocaleDateString()],
      ["Status", "approved"],
      ["Requested by", "Jane Doe"],
      ["Approved by", "Admin User"],
    ],
    styles: { fontSize: 9, font: tpl.font_family },
    headStyles: { fillColor: tableHeadFill(tpl) },
    columnStyles: { 0: { cellWidth: 55, fontStyle: "bold" } },
    margin: { left: tpl.margin_left, right: tpl.margin_right, bottom: tpl.margin_bottom },
  });
  const finalY = (doc as any).lastAutoTable.finalY + 16;
  doc.setFontSize(10);
  const colW = (pageWidth - tpl.margin_left - tpl.margin_right) / 3;
  ["Requester", "Approver", "Security"].forEach((label, i) => {
    const x = tpl.margin_left + colW * i;
    doc.text("_________________________", x, finalY);
    doc.text(`${label} signature`, x, finalY + 6);
  });
  applyTemplateChrome(doc, tpl);
  return doc.output("bloburl") as unknown as string;
}

function AppearancePanel() {
  const [theme, setTheme] = useState<StoredTheme>(() => loadStoredTheme());
  const apply = (next: StoredTheme) => { setTheme(next); saveStoredTheme(next); };
  const current = THEME_PRESETS.find((p) => p.id === theme.presetId) ?? THEME_PRESETS[0];
  return (
    <div className="space-y-5">
      <div>
        <p className="text-sm font-medium">Color theme</p>
        <p className="text-xs text-muted-foreground">Choose a preset or pick a custom primary color. Applies instantly across the app for your account.</p>
      </div>
      <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">
        {THEME_PRESETS.map((p) => {
          const active = p.id === theme.presetId;
          return (
            <button
              key={p.id}
              type="button"
              onClick={() => apply({ presetId: p.id, primary: undefined })}
              className={`rounded-lg border p-3 text-left transition ${active ? "ring-2 ring-primary border-primary" : "hover:bg-muted/40"}`}
            >
              <div className="mb-2 flex gap-1">
                <span className="h-5 w-5 rounded" style={{ background: p.primary }} />
                <span className="h-5 w-5 rounded" style={{ background: p.accent }} />
                <span className="h-5 w-5 rounded" style={{ background: p.sidebar }} />
                <span className="h-5 w-5 rounded" style={{ background: p.sidebarPrimary }} />
              </div>
              <p className="text-sm font-medium">{p.name}</p>
            </button>
          );
        })}
      </div>
      <div className="space-y-2">
        <Label>Custom primary color (overrides preset primary)</Label>
        <div className="flex items-center gap-2">
          <input
            type="color"
            value={theme.primary || current.primary}
            onChange={(e) => apply({ presetId: theme.presetId, primary: e.target.value })}
            className="h-9 w-12 cursor-pointer rounded border bg-transparent"
          />
          <Input
            value={theme.primary || ""}
            placeholder={current.primary}
            onChange={(e) => apply({ presetId: theme.presetId, primary: e.target.value || undefined })}
            className="font-mono max-w-[180px]"
          />
          {theme.primary && (
            <Button variant="ghost" size="sm" onClick={() => apply({ presetId: theme.presetId, primary: undefined })}>
              Clear
            </Button>
          )}
        </div>
      </div>
      <div className="space-y-2 border-t pt-4">
        <p className="text-sm font-medium">App font</p>
        <p className="text-xs text-muted-foreground">Pick a typeface for the app interface. Loaded from Google Fonts.</p>
        <Select value={theme.fontId ?? "system"} onValueChange={(v) => apply({ ...theme, fontId: v })}>
          <SelectTrigger className="max-w-sm"><SelectValue /></SelectTrigger>
          <SelectContent className="max-h-80">
            {FONT_OPTIONS.map((f) => (
              <SelectItem key={f.id} value={f.id}>
                <span style={{ fontFamily: f.stack }}>{f.name}</span>
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
        <div className="rounded-md border bg-card p-3" style={{ fontFamily: (FONT_OPTIONS.find((f) => f.id === (theme.fontId ?? "system")) ?? FONT_OPTIONS[0]).stack }}>
          <p className="text-lg font-semibold">The quick brown fox jumps over the lazy dog.</p>
          <p className="text-sm text-muted-foreground">0123456789 — Sample heading and body in the selected font.</p>
        </div>
      </div>
      <div className="rounded-md border bg-muted/30 p-3 text-xs text-muted-foreground">
        Your theme is saved to this browser. PDF document branding is controlled separately on the other tabs.
      </div>
    </div>
  );
}

// ---------------- User Guides ----------------

type GuideSection = { heading: string; body: string[] };
type GuideModule = {
  id: string;
  name: string;
  description: string;
  sections: GuideSection[];
};

const USER_GUIDES: GuideModule[] = [
  {
    id: "getting-started",
    name: "Getting Started",
    description: "First-time orientation, sign-in, navigation, and where to find things.",
    sections: [
      { heading: "Signing in", body: [
        "Open the system URL provided by your administrator.",
        "Enter your email and password and click Sign in. If you have forgotten your password, use the Reset link.",
        "On first sign-in, complete your profile (full name, phone, branch) from the user menu in the top-right corner.",
      ]},
      { heading: "Navigating modules", body: [
        "Use the left sidebar to switch between modules: Dashboard, Assets, Movements, Maintenance, Depreciation, Verification, Reports, Settings.",
        "Only modules you have permission to see will appear. Ask an administrator if a module is missing.",
        "The bell icon in the top bar shows in-app notifications for approvals, gate passes, and depreciation alerts.",
      ]},
      { heading: "Dashboard tiles", body: [
        "Tiles summarize totals (asset count, NBV, gate passes out, pending approvals). Click a tile to drill into its module.",
        "The Pending approvals card lists items waiting on you; click View details to act on them.",
      ]},
    ],
  },
  {
    id: "assets",
    name: "Asset Register",
    description: "Adding, editing, tagging, and viewing the history of fixed assets.",
    sections: [
      { heading: "Adding an asset", body: [
        "Go to Assets → New asset.",
        "Fill in tag, name, category, branch, location, purchase date, purchase value, and depreciation method.",
        "Attach invoices or photos under the Attachments tab after saving.",
      ]},
      { heading: "Editing an asset", body: [
        "Click any asset row to open its detail view, then use the Edit button.",
        "Changes are recorded in the audit trail and visible on the Verification tab.",
      ]},
      { heading: "Deleting an asset", body: [
        "Click the trash icon. A deletion request is created and must be approved by a user with approve_asset_deletion permission. State a reason; an approver will review and approve or reject.",
      ]},
    ],
  },
  {
    id: "movements",
    name: "Movements & Transfers",
    description: "Requesting and approving asset moves between branches/locations.",
    sections: [
      { heading: "Raising a movement request", body: [
        "Open the asset, click Move/Transfer.",
        "Pick the destination branch and location, add a reason, and submit.",
        "The request appears in Pending approvals for authorized reviewers.",
      ]},
      { heading: "Approval", body: [
        "Open the request from the dashboard or the Approvals queue.",
        "Review details (resolved to branch/location/asset names) and Approve or Reject with a comment.",
        "Approved moves immediately update the asset's branch/location and write to the audit trail.",
      ]},
    ],
  },
  {
    id: "gate-pass",
    name: "Gate Pass Management",
    description: "Permission to take assets outside the organization premises.",
    sections: [
      { heading: "Requesting a gate pass", body: [
        "Go to Gate Pass → New request.",
        "Pick the asset, give a reason, destination, expected return date, and optional attachment.",
        "Submit. The status starts as Pending until an authorized user approves.",
      ]},
      { heading: "Approval & checkout", body: [
        "An authorized reviewer Approves or Rejects. On approval a unique Gate Pass Number is generated.",
        "Security personnel verify the printed pass at the gate; the asset status becomes Checked out.",
      ]},
      { heading: "Returning the asset", body: [
        "On return, the custodian marks the pass Returned and verifies the asset condition.",
        "Asset status reverts to Available/In Custody. The full timeline is in the audit trail.",
      ]},
    ],
  },
  {
    id: "depreciation",
    name: "Depreciation",
    description: "Running depreciation, viewing NBV, handling missed and failed runs.",
    sections: [
      { heading: "Running depreciation", body: [
        "Go to Depreciation → Run depreciation.",
        "Pick a frequency (monthly/quarterly/annually) — the previous period is pre-filled.",
        "Tick assets to include, or use Missed only to catch up assets that were skipped.",
        "Click Run for N asset(s). The system posts entries and updates accumulated depreciation.",
      ]},
      { heading: "Alerts & failed runs", body: [
        "The Alerts tab lists failed/stuck runs, missing periods, and assets at residual.",
        "Use the filters (kind, asset, date range, search) to narrow the list.",
        "Click any failed-run alert to open the run dialog. It shows the failure reason, full stack trace (when available) and the step-by-step Run logs.",
        "You also receive in-app notifications when a run fails — click the notification to jump straight to the failure.",
      ]},
      { heading: "NBV & reports", body: [
        "NBV report, Accumulated, and By category tabs offer downloadable Excel/PDF reports.",
        "Click any asset row to open its insights dialog (history, missed periods, forecast).",
      ]},
    ],
  },
  {
    id: "verification",
    name: "Fixed Asset Verification",
    description: "Physically verifying assets, recording condition and custodian changes.",
    sections: [
      { heading: "Starting a verification round", body: [
        "Go to Verification, choose a branch.",
        "Scan or search assets one by one.",
      ]},
      { heading: "Recording results", body: [
        "Edit condition, custodian, and location as needed; save.",
        "The Verification activity report shows what changed; use the Compare dialog for a side-by-side diff with the previous verification.",
        "Changed fields link directly to the audit trail.",
      ]},
    ],
  },
  {
    id: "reports",
    name: "Reports",
    description: "Generating, previewing, and exporting all system reports.",
    sections: [
      { heading: "Available reports", body: [
        "Register, Movements, Retire/Dispose, Maintenance, Approvals, Verification, Depreciation, Gate Passes — each on its own tab.",
        "Apply filters at the top (branch, category, date range) before exporting.",
      ]},
      { heading: "Exporting", body: [
        "Each report has Excel and PDF download buttons. Use Preview to review before saving.",
        "Exports use the company branding configured under Settings → Document Template.",
      ]},
    ],
  },
  {
    id: "approvals",
    name: "Approvals & Requisitions",
    description: "Reviewing and acting on pending requests across the system.",
    sections: [
      { heading: "Where they appear", body: [
        "Pending requests appear on the Dashboard Pending approvals card and counts in the top-bar bell.",
        "When you Approve or Reject, the item disappears immediately and counters update.",
      ]},
      { heading: "Self-approval", body: [
        "Admins can approve their own requests. Other users need the approve_own_request right.",
      ]},
    ],
  },
  {
    id: "settings",
    name: "Settings & Branding",
    description: "Configuring document branding, theme, fonts, and downloading these guides.",
    sections: [
      { heading: "Document Template", body: [
        "Customize logo, header/footer, watermark, layout, paper size — preview updates live.",
        "Click Save changes to apply across all PDFs generated by the system.",
      ]},
      { heading: "Appearance (theme & font)", body: [
        "Pick a color preset or set a custom primary color; choose an interface font from the curated list.",
        "Theme is saved to your browser only — it does not affect other users.",
      ]},
      { heading: "User guides", body: [
        "This tab. Click Download PDF next to any module to get a printable how-to guide for that module, or download the full guide for the whole system.",
      ]},
    ],
  },
];

function UserGuidesPanel() {
  const downloadGuide = async (modules: GuideModule[], filename: string, title: string) => {
    const template = await loadTemplate();
    const { doc, startY, pageWidth, pageHeight, template: t } = createBrandedPdf({
      template, title, subtitle: "User guide",
    });
    let y = startY;
    const left = t.margin_left;
    const right = pageWidth - t.margin_right;
    const wrap = (text: string, size: number, bold = false) => {
      doc.setFont(t.font_family, bold ? "bold" : "normal");
      doc.setFontSize(size);
      const lines = doc.splitTextToSize(text, right - left);
      lines.forEach((ln: string) => {
        if (y > pageHeight - t.margin_bottom - 6) { doc.addPage(); y = t.margin_top; }
        doc.text(ln, left, y);
        y += size * 0.5 + 1.2;
      });
    };
    for (const m of modules) {
      if (y > pageHeight - t.margin_bottom - 30) { doc.addPage(); y = t.margin_top; }
      y += 2;
      wrap(m.name, 14, true);
      wrap(m.description, 9);
      y += 1;
      for (const s of m.sections) {
        y += 1;
        wrap(s.heading, 11, true);
        s.body.forEach((p, i) => wrap(`${i + 1}. ${p}`, 9));
      }
      y += 4;
    }
    applyTemplateChrome(doc, t);
    doc.save(filename);
  };

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-center justify-between gap-2">
        <div>
          <p className="text-sm font-medium">How to use the system</p>
          <p className="text-xs text-muted-foreground">Download a concise PDF guide for any module, or the full guide.</p>
        </div>
        <Button onClick={() => downloadGuide(USER_GUIDES, "user-guide-full.pdf", "System User Guide")}>
          Download full guide (PDF)
        </Button>
      </div>
      <div className="grid gap-2 sm:grid-cols-2">
        {USER_GUIDES.map((m) => (
          <Card key={m.id} className="flex items-start justify-between gap-3 p-3">
            <div className="min-w-0 flex-1">
              <p className="text-sm font-semibold">{m.name}</p>
              <p className="mt-0.5 text-xs text-muted-foreground">{m.description}</p>
            </div>
            <Button
              size="sm"
              variant="outline"
              onClick={() => downloadGuide([m], `user-guide-${m.id}.pdf`, `${m.name} — User Guide`)}
            >
              PDF
            </Button>
          </Card>
        ))}
      </div>
    </div>
  );
}

