import { useEffect, useRef, useState } from "react";
import { createFileRoute, Navigate } from "@tanstack/react-router";
import { useAuth } from "@/hooks/use-auth";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { Slider } from "@/components/ui/slider";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Settings as SettingsIcon, Upload, X, RefreshCw, Save } from "lucide-react";
import { toast } from "sonner";
import autoTable from "jspdf-autotable";
import {
  loadTemplate, invalidateTemplateCache, createBrandedPdf, applyTemplateChrome, tableHeadFill,
  DEFAULT_TEMPLATE, type DocumentTemplate,
} from "@/lib/pdf-template";
import {
  THEME_PRESETS, loadStoredTheme, saveStoredTheme, type StoredTheme,
} from "@/lib/theme";

export const Route = createFileRoute("/_app/settings")({
  component: SettingsPage,
});

function SettingsPage() {
  const { loading, canView, canDo } = useAuth();
  const canManage = canDo("manage_document_templates");
  const [tpl, setTpl] = useState<DocumentTemplate | null>(null);
  const [saving, setSaving] = useState(false);
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);
  const previewTimer = useRef<any>(null);

  useEffect(() => { loadTemplate(true).then(setTpl); }, []);

  // Debounced live preview
  useEffect(() => {
    if (!tpl) return;
    clearTimeout(previewTimer.current);
    previewTimer.current = setTimeout(() => generatePreview(tpl).then(setPreviewUrl), 250);
    return () => clearTimeout(previewTimer.current);
  }, [tpl]);

  if (loading) return null;
  if (!canView("settings")) return <Navigate to="/dashboard" />;
  if (!tpl) return <div className="p-6 text-sm text-muted-foreground">Loading template…</div>;

  const set = <K extends keyof DocumentTemplate>(k: K, v: DocumentTemplate[K]) =>
    setTpl((t) => (t ? { ...t, [k]: v } : t));

  const onPickFile = async (key: "logo_data_url" | "watermark_image_data_url", file: File) => {
    const dataUrl = await fileToDataUrl(file);
    set(key, dataUrl);
  };

  const save = async () => {
    if (!tpl) return;
    if (!canManage) { toast.error("You don't have permission to edit templates"); return; }
    setSaving(true);
    const { id, created_at, updated_at, ...rest } = tpl as any;
    const payload = { ...rest, updated_by: (await supabase.auth.getUser()).data.user?.id };
    const { error } = await supabase
      .from("document_templates" as any)
      .update(payload)
      .eq("id", id);
    setSaving(false);
    if (error) { toast.error(error.message); return; }
    invalidateTemplateCache();
    toast.success("Template saved · applies to all new PDFs");
  };

  const reset = () => setTpl((t) => (t ? { ...DEFAULT_TEMPLATE, id: t.id, name: t.name } : t));

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h1 className="flex items-center gap-2 text-2xl font-bold tracking-tight">
            <SettingsIcon className="h-6 w-6" /> Document Template
          </h1>
          <p className="text-sm text-muted-foreground">
            Branding & layout applied to every PDF generated by the system (reports, gate passes, asset details, depreciation schedules).
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="outline" onClick={reset} disabled={!canManage}><RefreshCw className="mr-2 h-4 w-4" />Reset</Button>
          <Button onClick={save} disabled={!canManage || saving}><Save className="mr-2 h-4 w-4" />{saving ? "Saving…" : "Save changes"}</Button>
        </div>
      </div>

      {!canManage && (
        <Card className="border-amber-300 bg-amber-50 p-3 text-sm text-amber-900">
          You can preview the active template but you don't have the <strong>manage_document_templates</strong> right needed to edit it. Ask an administrator to grant it from the Users module.
        </Card>
      )}

      <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(0,1fr)]">
        <Card className="p-4">
          <Tabs defaultValue="brand">
            <TabsList className="grid grid-cols-5">
              <TabsTrigger value="brand">Branding</TabsTrigger>
              <TabsTrigger value="header">Header / Footer</TabsTrigger>
              <TabsTrigger value="watermark">Watermark</TabsTrigger>
              <TabsTrigger value="layout">Layout</TabsTrigger>
              <TabsTrigger value="appearance">Appearance</TabsTrigger>
            </TabsList>

            <fieldset disabled={!canManage} className="space-y-4">

            <TabsContent value="brand" className="space-y-4 pt-4">
              <div className="space-y-2">
                <Label>Organization name</Label>
                <Input value={tpl.organization_name} onChange={(e) => set("organization_name", e.target.value)} />
              </div>
              <div className="space-y-2">
                <Label>Logo</Label>
                {tpl.logo_data_url ? (
                  <div className="flex items-center gap-3 rounded border p-2">
                    <img src={tpl.logo_data_url} alt="Logo" className="h-12 w-auto rounded bg-white" />
                    <Button size="sm" variant="ghost" onClick={() => set("logo_data_url", null)}>
                      <X className="mr-1 h-4 w-4" /> Remove
                    </Button>
                  </div>
                ) : (
                  <label className="flex cursor-pointer items-center gap-2 rounded border border-dashed p-3 text-sm text-muted-foreground hover:bg-muted/50">
                    <Upload className="h-4 w-4" /> Upload PNG/JPG (recommended &lt; 200 KB)
                    <input type="file" accept="image/*" className="hidden" onChange={(e) => e.target.files?.[0] && onPickFile("logo_data_url", e.target.files[0])} />
                  </label>
                )}
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div className="space-y-2">
                  <Label>Logo position</Label>
                  <Select value={tpl.logo_position} onValueChange={(v) => set("logo_position", v as any)}>
                    <SelectTrigger><SelectValue /></SelectTrigger>
                    <SelectContent>
                      <SelectItem value="left">Left</SelectItem>
                      <SelectItem value="center">Center</SelectItem>
                      <SelectItem value="right">Right</SelectItem>
                      <SelectItem value="none">Hidden</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-2">
                  <Label>Logo max height (mm) — {tpl.logo_max_height}</Label>
                  <Slider value={[tpl.logo_max_height]} min={6} max={40} step={1} onValueChange={([v]) => set("logo_max_height", v)} />
                </div>
              </div>
              <div className="space-y-2">
                <Label>Primary color</Label>
                <div className="flex items-center gap-2">
                  <input type="color" value={tpl.primary_color} onChange={(e) => set("primary_color", e.target.value)} className="h-9 w-12 cursor-pointer rounded border bg-transparent" />
                  <Input value={tpl.primary_color} onChange={(e) => set("primary_color", e.target.value)} className="font-mono" />
                </div>
              </div>
            </TabsContent>

            <TabsContent value="header" className="space-y-4 pt-4">
              <div className="flex items-center justify-between">
                <Label>Show header</Label>
                <Switch checked={tpl.header_show} onCheckedChange={(v) => set("header_show", v)} />
              </div>
              <div className="space-y-2">
                <Label>Header text (right side, falls back to organization name)</Label>
                <Input value={tpl.header_text} onChange={(e) => set("header_text", e.target.value)} placeholder="e.g. Acme Holdings Ltd · Confidential" />
              </div>
              <div className="flex items-center justify-between">
                <Label>Show footer</Label>
                <Switch checked={tpl.footer_show} onCheckedChange={(v) => set("footer_show", v)} />
              </div>
              <div className="space-y-2">
                <Label>Footer text</Label>
                <Textarea rows={2} value={tpl.footer_text} onChange={(e) => set("footer_text", e.target.value)} placeholder="© 2026 Acme Holdings · Generated by AssetFlow" />
              </div>
              <div className="flex items-center justify-between">
                <Label>Show page numbers</Label>
                <Switch checked={tpl.show_page_numbers} onCheckedChange={(v) => set("show_page_numbers", v)} />
              </div>
              <div className="flex items-center justify-between">
                <Label>Show generated-at timestamp</Label>
                <Switch checked={tpl.show_generated_at} onCheckedChange={(v) => set("show_generated_at", v)} />
              </div>
            </TabsContent>

            <TabsContent value="watermark" className="space-y-4 pt-4">
              <div className="space-y-2">
                <Label>Watermark text</Label>
                <Input value={tpl.watermark_text} onChange={(e) => set("watermark_text", e.target.value)} placeholder="e.g. CONFIDENTIAL" />
              </div>
              <div className="space-y-2">
                <Label>Watermark image (optional, overlay)</Label>
                {tpl.watermark_image_data_url ? (
                  <div className="flex items-center gap-3 rounded border p-2">
                    <img src={tpl.watermark_image_data_url} alt="Watermark" className="h-12 w-auto rounded bg-white" />
                    <Button size="sm" variant="ghost" onClick={() => set("watermark_image_data_url", null)}>
                      <X className="mr-1 h-4 w-4" /> Remove
                    </Button>
                  </div>
                ) : (
                  <label className="flex cursor-pointer items-center gap-2 rounded border border-dashed p-3 text-sm text-muted-foreground hover:bg-muted/50">
                    <Upload className="h-4 w-4" /> Upload watermark image
                    <input type="file" accept="image/*" className="hidden" onChange={(e) => e.target.files?.[0] && onPickFile("watermark_image_data_url", e.target.files[0])} />
                  </label>
                )}
              </div>
              <div className="space-y-2">
                <Label>Position</Label>
                <Select value={tpl.watermark_position} onValueChange={(v) => set("watermark_position", v as any)}>
                  <SelectTrigger><SelectValue /></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="none">None</SelectItem>
                    <SelectItem value="center">Center</SelectItem>
                    <SelectItem value="diagonal">Diagonal</SelectItem>
                    <SelectItem value="repeated">Repeated pattern</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label>Opacity — {Math.round(tpl.watermark_opacity * 100)}%</Label>
                <Slider value={[tpl.watermark_opacity * 100]} min={2} max={60} step={1} onValueChange={([v]) => set("watermark_opacity", v / 100)} />
              </div>
            </TabsContent>

            <TabsContent value="layout" className="space-y-4 pt-4">
              <div className="grid grid-cols-2 gap-3">
                <div className="space-y-2">
                  <Label>Font family</Label>
                  <Select value={tpl.font_family} onValueChange={(v) => set("font_family", v as any)}>
                    <SelectTrigger><SelectValue /></SelectTrigger>
                    <SelectContent>
                      <SelectItem value="helvetica">Helvetica (sans-serif)</SelectItem>
                      <SelectItem value="times">Times (serif)</SelectItem>
                      <SelectItem value="courier">Courier (monospace)</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-2">
                  <Label>Base font size — {tpl.base_font_size}pt</Label>
                  <Slider value={[tpl.base_font_size]} min={7} max={16} step={1} onValueChange={([v]) => set("base_font_size", v)} />
                </div>
                <div className="space-y-2">
                  <Label>Orientation</Label>
                  <Select value={tpl.orientation} onValueChange={(v) => set("orientation", v as any)}>
                    <SelectTrigger><SelectValue /></SelectTrigger>
                    <SelectContent>
                      <SelectItem value="portrait">Portrait</SelectItem>
                      <SelectItem value="landscape">Landscape</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-2">
                  <Label>Paper size</Label>
                  <Select value={tpl.paper_size} onValueChange={(v) => set("paper_size", v as any)}>
                    <SelectTrigger><SelectValue /></SelectTrigger>
                    <SelectContent>
                      <SelectItem value="a4">A4</SelectItem>
                      <SelectItem value="letter">Letter</SelectItem>
                      <SelectItem value="legal">Legal</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>
              <div className="grid grid-cols-4 gap-3">
                {(["margin_top", "margin_right", "margin_bottom", "margin_left"] as const).map((k) => (
                  <div className="space-y-2" key={k}>
                    <Label className="capitalize">{k.replace("margin_", "")} (mm)</Label>
                    <Input type="number" min={0} max={60} value={tpl[k]} onChange={(e) => set(k, Number(e.target.value))} />
                  </div>
                ))}
              </div>
              <p className="text-xs text-muted-foreground">
                Note: list-style PDFs (asset list, reports) keep their landscape orientation; portrait/landscape choice here is the default for single-record documents.
              </p>
            </TabsContent>

            </fieldset>

            <TabsContent value="appearance" className="space-y-4 pt-4">
              <AppearancePanel />
            </TabsContent>
          </Tabs>
        </Card>

        <Card className="flex h-[800px] flex-col p-3">
          <div className="mb-2 flex items-center justify-between">
            <p className="text-sm font-medium">Live preview (sample gate pass)</p>
            <p className="text-xs text-muted-foreground">Updates as you type</p>
          </div>
          {previewUrl ? (
            <iframe key={previewUrl} src={previewUrl} className="h-full w-full flex-1 rounded border bg-white" title="PDF preview" />
          ) : (
            <div className="flex flex-1 items-center justify-center text-sm text-muted-foreground">Rendering…</div>
          )}
        </Card>
      </div>
    </div>
  );
}

function fileToDataUrl(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const r = new FileReader();
    r.onload = () => resolve(String(r.result));
    r.onerror = reject;
    r.readAsDataURL(file);
  });
}

async function generatePreview(tpl: DocumentTemplate): Promise<string> {
  const { doc, startY, pageWidth } = createBrandedPdf({
    template: tpl,
    title: "SAMPLE GATE PASS",
    subtitle: "Pass No: GP-2026-000123",
  });
  autoTable(doc, {
    startY,
    head: [["Field", "Value"]],
    body: [
      ["Asset", "LP-001 · Dell Latitude 7440"],
      ["Branch", "Head Office"],
      ["Destination", "Client site — Garden City"],
      ["Reason", "Field installation"],
      ["Expected return", new Date(Date.now() + 5 * 86400000).toLocaleDateString()],
      ["Status", "approved"],
      ["Requested by", "Jane Doe"],
      ["Approved by", "Admin User"],
    ],
    styles: { fontSize: 9, font: tpl.font_family },
    headStyles: { fillColor: tableHeadFill(tpl) },
    columnStyles: { 0: { cellWidth: 55, fontStyle: "bold" } },
    margin: { left: tpl.margin_left, right: tpl.margin_right, bottom: tpl.margin_bottom },
  });
  const finalY = (doc as any).lastAutoTable.finalY + 16;
  doc.setFontSize(10);
  const colW = (pageWidth - tpl.margin_left - tpl.margin_right) / 3;
  ["Requester", "Approver", "Security"].forEach((label, i) => {
    const x = tpl.margin_left + colW * i;
    doc.text("_________________________", x, finalY);
    doc.text(`${label} signature`, x, finalY + 6);
  });
  applyTemplateChrome(doc, tpl);
  return doc.output("bloburl") as unknown as string;
}
