BEGIN;

DELETE FROM public.geo_places WHERE source IN ('KNBS current counties','Tanzania NBS 2025','Rwanda NISR 2026','ZamStats 2026','Malawi NSO 2024','ZIMSTAT 2023-24');

INSERT INTO public.geo_places(
 geoname_id,country_code,parent_geoname_id,name,ascii_name,feature_class,feature_code,admin_level,
 admin1_code,admin2_code,admin3_code,admin4_code,latitude,longitude,population,display_path,source
) VALUES
(981000001,'KE',NULL,'Mombasa','Mombasa','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Mombasa County · KE','KNBS current counties'),
(981000002,'KE',NULL,'Kwale','Kwale','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Kwale County · KE','KNBS current counties'),
(981000003,'KE',NULL,'Kilifi','Kilifi','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Kilifi County · KE','KNBS current counties'),
(981000004,'KE',NULL,'Tana River','Tana River','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Tana River County · KE','KNBS current counties'),
(981000005,'KE',NULL,'Lamu','Lamu','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Lamu County · KE','KNBS current counties'),
(981000006,'KE',NULL,'Taita-Taveta','Taita-Taveta','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Taita-Taveta County · KE','KNBS current counties'),
(981000007,'KE',NULL,'Garissa','Garissa','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Garissa County · KE','KNBS current counties'),
(981000008,'KE',NULL,'Wajir','Wajir','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Wajir County · KE','KNBS current counties'),
(981000009,'KE',NULL,'Mandera','Mandera','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Mandera County · KE','KNBS current counties'),
(981000010,'KE',NULL,'Marsabit','Marsabit','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Marsabit County · KE','KNBS current counties'),
(981000011,'KE',NULL,'Isiolo','Isiolo','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Isiolo County · KE','KNBS current counties'),
(981000012,'KE',NULL,'Meru','Meru','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Meru County · KE','KNBS current counties'),
(981000013,'KE',NULL,'Tharaka-Nithi','Tharaka-Nithi','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Tharaka-Nithi County · KE','KNBS current counties'),
(981000014,'KE',NULL,'Embu','Embu','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Embu County · KE','KNBS current counties'),
(981000015,'KE',NULL,'Kitui','Kitui','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Kitui County · KE','KNBS current counties'),
(981000016,'KE',NULL,'Machakos','Machakos','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Machakos County · KE','KNBS current counties'),
(981000017,'KE',NULL,'Makueni','Makueni','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Makueni County · KE','KNBS current counties'),
(981000018,'KE',NULL,'Nyandarua','Nyandarua','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Nyandarua County · KE','KNBS current counties'),
(981000019,'KE',NULL,'Nyeri','Nyeri','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Nyeri County · KE','KNBS current counties'),
(981000020,'KE',NULL,'Kirinyaga','Kirinyaga','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Kirinyaga County · KE','KNBS current counties'),
(981000021,'KE',NULL,'Murang''a','Murang''a','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Murang''a County · KE','KNBS current counties'),
(981000022,'KE',NULL,'Kiambu','Kiambu','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Kiambu County · KE','KNBS current counties'),
(981000023,'KE',NULL,'Turkana','Turkana','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Turkana County · KE','KNBS current counties'),
(981000024,'KE',NULL,'West Pokot','West Pokot','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'West Pokot County · KE','KNBS current counties'),
(981000025,'KE',NULL,'Samburu','Samburu','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Samburu County · KE','KNBS current counties'),
(981000026,'KE',NULL,'Trans Nzoia','Trans Nzoia','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Trans Nzoia County · KE','KNBS current counties'),
(981000027,'KE',NULL,'Uasin Gishu','Uasin Gishu','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Uasin Gishu County · KE','KNBS current counties'),
(981000028,'KE',NULL,'Elgeyo-Marakwet','Elgeyo-Marakwet','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Elgeyo-Marakwet County · KE','KNBS current counties'),
(981000029,'KE',NULL,'Nandi','Nandi','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Nandi County · KE','KNBS current counties'),
(981000030,'KE',NULL,'Baringo','Baringo','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Baringo County · KE','KNBS current counties'),
(981000031,'KE',NULL,'Laikipia','Laikipia','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Laikipia County · KE','KNBS current counties'),
(981000032,'KE',NULL,'Nakuru','Nakuru','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Nakuru County · KE','KNBS current counties'),
(981000033,'KE',NULL,'Narok','Narok','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Narok County · KE','KNBS current counties'),
(981000034,'KE',NULL,'Kajiado','Kajiado','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Kajiado County · KE','KNBS current counties'),
(981000035,'KE',NULL,'Kericho','Kericho','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Kericho County · KE','KNBS current counties'),
(981000036,'KE',NULL,'Bomet','Bomet','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Bomet County · KE','KNBS current counties'),
(981000037,'KE',NULL,'Kakamega','Kakamega','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Kakamega County · KE','KNBS current counties'),
(981000038,'KE',NULL,'Vihiga','Vihiga','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Vihiga County · KE','KNBS current counties'),
(981000039,'KE',NULL,'Bungoma','Bungoma','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Bungoma County · KE','KNBS current counties'),
(981000040,'KE',NULL,'Busia','Busia','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Busia County · KE','KNBS current counties'),
(981000041,'KE',NULL,'Siaya','Siaya','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Siaya County · KE','KNBS current counties'),
(981000042,'KE',NULL,'Kisumu','Kisumu','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Kisumu County · KE','KNBS current counties'),
(981000043,'KE',NULL,'Homa Bay','Homa Bay','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Homa Bay County · KE','KNBS current counties'),
(981000044,'KE',NULL,'Migori','Migori','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Migori County · KE','KNBS current counties'),
(981000045,'KE',NULL,'Kisii','Kisii','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Kisii County · KE','KNBS current counties'),
(981000046,'KE',NULL,'Nyamira','Nyamira','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Nyamira County · KE','KNBS current counties'),
(981000047,'KE',NULL,'Nairobi City','Nairobi City','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Nairobi City County · KE','KNBS current counties'),
(982000001,'TZ',NULL,'Arusha','Arusha','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Arusha Region · TZ','Tanzania NBS 2025'),
(982000002,'TZ',NULL,'Dar es Salaam','Dar es Salaam','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Dar es Salaam Region · TZ','Tanzania NBS 2025'),
(982000003,'TZ',NULL,'Dodoma','Dodoma','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Dodoma Region · TZ','Tanzania NBS 2025'),
(982000004,'TZ',NULL,'Geita','Geita','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Geita Region · TZ','Tanzania NBS 2025'),
(982000005,'TZ',NULL,'Iringa','Iringa','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Iringa Region · TZ','Tanzania NBS 2025'),
(982000006,'TZ',NULL,'Kagera','Kagera','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Kagera Region · TZ','Tanzania NBS 2025'),
(982000007,'TZ',NULL,'Kaskazini Pemba','Kaskazini Pemba','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Kaskazini Pemba Region · TZ','Tanzania NBS 2025'),
(982000008,'TZ',NULL,'Kaskazini Unguja','Kaskazini Unguja','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Kaskazini Unguja Region · TZ','Tanzania NBS 2025'),
(982000009,'TZ',NULL,'Katavi','Katavi','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Katavi Region · TZ','Tanzania NBS 2025'),
(982000010,'TZ',NULL,'Kigoma','Kigoma','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Kigoma Region · TZ','Tanzania NBS 2025'),
(982000011,'TZ',NULL,'Kilimanjaro','Kilimanjaro','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Kilimanjaro Region · TZ','Tanzania NBS 2025'),
(982000012,'TZ',NULL,'Kusini Pemba','Kusini Pemba','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Kusini Pemba Region · TZ','Tanzania NBS 2025'),
(982000013,'TZ',NULL,'Kusini Unguja','Kusini Unguja','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Kusini Unguja Region · TZ','Tanzania NBS 2025'),
(982000014,'TZ',NULL,'Lindi','Lindi','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Lindi Region · TZ','Tanzania NBS 2025'),
(982000015,'TZ',NULL,'Manyara','Manyara','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Manyara Region · TZ','Tanzania NBS 2025'),
(982000016,'TZ',NULL,'Mara','Mara','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Mara Region · TZ','Tanzania NBS 2025'),
(982000017,'TZ',NULL,'Mbeya','Mbeya','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Mbeya Region · TZ','Tanzania NBS 2025'),
(982000018,'TZ',NULL,'Mjini Magharibi','Mjini Magharibi','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Mjini Magharibi Region · TZ','Tanzania NBS 2025'),
(982000019,'TZ',NULL,'Morogoro','Morogoro','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Morogoro Region · TZ','Tanzania NBS 2025'),
(982000020,'TZ',NULL,'Mtwara','Mtwara','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Mtwara Region · TZ','Tanzania NBS 2025'),
(982000021,'TZ',NULL,'Mwanza','Mwanza','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Mwanza Region · TZ','Tanzania NBS 2025'),
(982000022,'TZ',NULL,'Njombe','Njombe','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Njombe Region · TZ','Tanzania NBS 2025'),
(982000023,'TZ',NULL,'Pwani','Pwani','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Pwani Region · TZ','Tanzania NBS 2025'),
(982000024,'TZ',NULL,'Rukwa','Rukwa','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Rukwa Region · TZ','Tanzania NBS 2025'),
(982000025,'TZ',NULL,'Ruvuma','Ruvuma','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Ruvuma Region · TZ','Tanzania NBS 2025'),
(982000026,'TZ',NULL,'Shinyanga','Shinyanga','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Shinyanga Region · TZ','Tanzania NBS 2025'),
(982000027,'TZ',NULL,'Simiyu','Simiyu','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Simiyu Region · TZ','Tanzania NBS 2025'),
(982000028,'TZ',NULL,'Singida','Singida','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Singida Region · TZ','Tanzania NBS 2025'),
(982000029,'TZ',NULL,'Songwe','Songwe','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Songwe Region · TZ','Tanzania NBS 2025'),
(982000030,'TZ',NULL,'Tabora','Tabora','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Tabora Region · TZ','Tanzania NBS 2025'),
(982000031,'TZ',NULL,'Tanga','Tanga','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Tanga Region · TZ','Tanzania NBS 2025'),
(983000001,'RW',NULL,'Gasabo','Gasabo','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Gasabo District · RW','Rwanda NISR 2026'),
(983000002,'RW',NULL,'Kicukiro','Kicukiro','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Kicukiro District · RW','Rwanda NISR 2026'),
(983000003,'RW',NULL,'Nyarugenge','Nyarugenge','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Nyarugenge District · RW','Rwanda NISR 2026'),
(983000004,'RW',NULL,'Gisagara','Gisagara','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Gisagara District · RW','Rwanda NISR 2026'),
(983000005,'RW',NULL,'Huye','Huye','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Huye District · RW','Rwanda NISR 2026'),
(983000006,'RW',NULL,'Kamonyi','Kamonyi','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Kamonyi District · RW','Rwanda NISR 2026'),
(983000007,'RW',NULL,'Muhanga','Muhanga','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Muhanga District · RW','Rwanda NISR 2026'),
(983000008,'RW',NULL,'Nyamagabe','Nyamagabe','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Nyamagabe District · RW','Rwanda NISR 2026'),
(983000009,'RW',NULL,'Nyanza','Nyanza','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Nyanza District · RW','Rwanda NISR 2026'),
(983000010,'RW',NULL,'Nyaruguru','Nyaruguru','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Nyaruguru District · RW','Rwanda NISR 2026'),
(983000011,'RW',NULL,'Ruhango','Ruhango','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Ruhango District · RW','Rwanda NISR 2026'),
(983000012,'RW',NULL,'Karongi','Karongi','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Karongi District · RW','Rwanda NISR 2026'),
(983000013,'RW',NULL,'Ngororero','Ngororero','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Ngororero District · RW','Rwanda NISR 2026'),
(983000014,'RW',NULL,'Nyabihu','Nyabihu','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Nyabihu District · RW','Rwanda NISR 2026'),
(983000015,'RW',NULL,'Nyamasheke','Nyamasheke','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Nyamasheke District · RW','Rwanda NISR 2026'),
(983000016,'RW',NULL,'Rubavu','Rubavu','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Rubavu District · RW','Rwanda NISR 2026'),
(983000017,'RW',NULL,'Rusizi','Rusizi','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Rusizi District · RW','Rwanda NISR 2026'),
(983000018,'RW',NULL,'Rutsiro','Rutsiro','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Rutsiro District · RW','Rwanda NISR 2026'),
(983000019,'RW',NULL,'Burera','Burera','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Burera District · RW','Rwanda NISR 2026'),
(983000020,'RW',NULL,'Gakenke','Gakenke','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Gakenke District · RW','Rwanda NISR 2026'),
(983000021,'RW',NULL,'Gicumbi','Gicumbi','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Gicumbi District · RW','Rwanda NISR 2026'),
(983000022,'RW',NULL,'Musanze','Musanze','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Musanze District · RW','Rwanda NISR 2026'),
(983000023,'RW',NULL,'Rulindo','Rulindo','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Rulindo District · RW','Rwanda NISR 2026'),
(983000024,'RW',NULL,'Bugesera','Bugesera','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Bugesera District · RW','Rwanda NISR 2026'),
(983000025,'RW',NULL,'Gatsibo','Gatsibo','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Gatsibo District · RW','Rwanda NISR 2026'),
(983000026,'RW',NULL,'Kayonza','Kayonza','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Kayonza District · RW','Rwanda NISR 2026'),
(983000027,'RW',NULL,'Kirehe','Kirehe','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Kirehe District · RW','Rwanda NISR 2026'),
(983000028,'RW',NULL,'Ngoma','Ngoma','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Ngoma District · RW','Rwanda NISR 2026'),
(983000029,'RW',NULL,'Nyagatare','Nyagatare','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Nyagatare District · RW','Rwanda NISR 2026'),
(983000030,'RW',NULL,'Rwamagana','Rwamagana','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Rwamagana District · RW','Rwanda NISR 2026'),
(984000001,'ZM',NULL,'Central','Central','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Central Province · ZM','ZamStats 2026'),
(984000002,'ZM',NULL,'Copperbelt','Copperbelt','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Copperbelt Province · ZM','ZamStats 2026'),
(984000003,'ZM',NULL,'Eastern','Eastern','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Eastern Province · ZM','ZamStats 2026'),
(984000004,'ZM',NULL,'Luapula','Luapula','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Luapula Province · ZM','ZamStats 2026'),
(984000005,'ZM',NULL,'Lusaka','Lusaka','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Lusaka Province · ZM','ZamStats 2026'),
(984000006,'ZM',NULL,'Muchinga','Muchinga','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Muchinga Province · ZM','ZamStats 2026'),
(984000007,'ZM',NULL,'Northern','Northern','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Northern Province · ZM','ZamStats 2026'),
(984000008,'ZM',NULL,'North-Western','North-Western','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'North-Western Province · ZM','ZamStats 2026'),
(984000009,'ZM',NULL,'Southern','Southern','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Southern Province · ZM','ZamStats 2026'),
(984000010,'ZM',NULL,'Western','Western','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Western Province · ZM','ZamStats 2026'),
(985000001,'MW',NULL,'Chitipa','Chitipa','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Chitipa District · MW','Malawi NSO 2024'),
(985000002,'MW',NULL,'Karonga','Karonga','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Karonga District · MW','Malawi NSO 2024'),
(985000003,'MW',NULL,'Nkhata Bay','Nkhata Bay','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Nkhata Bay District · MW','Malawi NSO 2024'),
(985000004,'MW',NULL,'Rumphi','Rumphi','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Rumphi District · MW','Malawi NSO 2024'),
(985000005,'MW',NULL,'Mzimba','Mzimba','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Mzimba District · MW','Malawi NSO 2024'),
(985000006,'MW',NULL,'Likoma','Likoma','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Likoma District · MW','Malawi NSO 2024'),
(985000007,'MW',NULL,'Kasungu','Kasungu','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Kasungu District · MW','Malawi NSO 2024'),
(985000008,'MW',NULL,'Nkhotakota','Nkhotakota','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Nkhotakota District · MW','Malawi NSO 2024'),
(985000009,'MW',NULL,'Ntchisi','Ntchisi','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Ntchisi District · MW','Malawi NSO 2024'),
(985000010,'MW',NULL,'Dowa','Dowa','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Dowa District · MW','Malawi NSO 2024'),
(985000011,'MW',NULL,'Salima','Salima','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Salima District · MW','Malawi NSO 2024'),
(985000012,'MW',NULL,'Lilongwe','Lilongwe','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Lilongwe District · MW','Malawi NSO 2024'),
(985000013,'MW',NULL,'Mchinji','Mchinji','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Mchinji District · MW','Malawi NSO 2024'),
(985000014,'MW',NULL,'Dedza','Dedza','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Dedza District · MW','Malawi NSO 2024'),
(985000015,'MW',NULL,'Ntcheu','Ntcheu','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Ntcheu District · MW','Malawi NSO 2024'),
(985000016,'MW',NULL,'Mangochi','Mangochi','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Mangochi District · MW','Malawi NSO 2024'),
(985000017,'MW',NULL,'Machinga','Machinga','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Machinga District · MW','Malawi NSO 2024'),
(985000018,'MW',NULL,'Zomba','Zomba','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Zomba District · MW','Malawi NSO 2024'),
(985000019,'MW',NULL,'Chiradzulu','Chiradzulu','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Chiradzulu District · MW','Malawi NSO 2024'),
(985000020,'MW',NULL,'Blantyre','Blantyre','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Blantyre District · MW','Malawi NSO 2024'),
(985000021,'MW',NULL,'Mwanza','Mwanza','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Mwanza District · MW','Malawi NSO 2024'),
(985000022,'MW',NULL,'Thyolo','Thyolo','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Thyolo District · MW','Malawi NSO 2024'),
(985000023,'MW',NULL,'Mulanje','Mulanje','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Mulanje District · MW','Malawi NSO 2024'),
(985000024,'MW',NULL,'Phalombe','Phalombe','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Phalombe District · MW','Malawi NSO 2024'),
(985000025,'MW',NULL,'Chikwawa','Chikwawa','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Chikwawa District · MW','Malawi NSO 2024'),
(985000026,'MW',NULL,'Nsanje','Nsanje','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Nsanje District · MW','Malawi NSO 2024'),
(985000027,'MW',NULL,'Balaka','Balaka','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Balaka District · MW','Malawi NSO 2024'),
(985000028,'MW',NULL,'Neno','Neno','A','ADM2',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Neno District · MW','Malawi NSO 2024'),
(986000001,'ZW',NULL,'Manicaland','Manicaland','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Manicaland Province · ZW','ZIMSTAT 2023-24'),
(986000002,'ZW',NULL,'Mashonaland Central','Mashonaland Central','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Mashonaland Central Province · ZW','ZIMSTAT 2023-24'),
(986000003,'ZW',NULL,'Mashonaland East','Mashonaland East','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Mashonaland East Province · ZW','ZIMSTAT 2023-24'),
(986000004,'ZW',NULL,'Mashonaland West','Mashonaland West','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Mashonaland West Province · ZW','ZIMSTAT 2023-24'),
(986000005,'ZW',NULL,'Matabeleland North','Matabeleland North','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Matabeleland North Province · ZW','ZIMSTAT 2023-24'),
(986000006,'ZW',NULL,'Matabeleland South','Matabeleland South','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Matabeleland South Province · ZW','ZIMSTAT 2023-24'),
(986000007,'ZW',NULL,'Midlands','Midlands','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Midlands Province · ZW','ZIMSTAT 2023-24'),
(986000008,'ZW',NULL,'Masvingo','Masvingo','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Masvingo Province · ZW','ZIMSTAT 2023-24'),
(986000009,'ZW',NULL,'Harare','Harare','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Harare Province · ZW','ZIMSTAT 2023-24'),
(986000010,'ZW',NULL,'Bulawayo','Bulawayo','A','ADM1',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Bulawayo Province · ZW','ZIMSTAT 2023-24')
ON CONFLICT (geoname_id) DO UPDATE SET
 country_code=EXCLUDED.country_code, parent_geoname_id=EXCLUDED.parent_geoname_id,
 name=EXCLUDED.name, ascii_name=EXCLUDED.ascii_name, feature_class=EXCLUDED.feature_class,
 feature_code=EXCLUDED.feature_code, admin_level=EXCLUDED.admin_level, display_path=EXCLUDED.display_path,
 source=EXCLUDED.source, updated_at=now();

COMMIT;
